# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, verbose_name='twitter handle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=128, verbose_name='github handle'),
        ),
    ]
