# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 19:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170506_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=38, validators=[django.core.validators.RegexValidator(message='Bitte nur den Benutzername, nicht die Profil-Url.', regex='^[a-z\\d](?:[a-z\\d]|-(?=[a-z\\d]))*$')], verbose_name='Github Benutzername'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Bitte nur den Benutzername, ohne führendes @.', regex='^[a-zA-Z0-9_]+$')], verbose_name='Twitter Benutzername'),
        ),
    ]
