# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import roms.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('cover', models.ImageField(upload_to=roms.models.upload_cover_to, verbose_name='cover image')),
                ('binary', models.FileField(upload_to=roms.models.upload_binary_to, verbose_name='binary')),
                ('approved', models.BooleanField(verbose_name='approved')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
