# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import roms.models


class Migration(migrations.Migration):

    dependencies = [
        ('roms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rom',
            name='binary',
        ),
        migrations.AddField(
            model_name='rom',
            name='high_binary',
            field=models.FileField(default='', upload_to=roms.models.upload_binary_to, verbose_name='high binary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rom',
            name='low_binary',
            field=models.FileField(default='', upload_to=roms.models.upload_binary_to, verbose_name='low binary'),
            preserve_default=False,
        ),
    ]
