# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import roms.models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('roms', '0003_auto_20170506_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='rom',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rom',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='edit time'),
        ),
        migrations.AlterField(
            model_name='rom',
            name='cover',
            field=stdimage.models.StdImageField(upload_to=roms.models.upload_cover_to, validators=[stdimage.validators.MinSizeValidator(300, 300)], verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='rom',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
    ]
