# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roms', '0004_auto_20170508_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='rom',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
