# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roms', '0007_auto_20170524_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rom',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Beschreibung'),
        ),
    ]
