# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roms', '0008_auto_20170525_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='rom',
            name='download_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
